# Generated by Django 4.2 on 2024-07-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('directorName', models.CharField(max_length=200)),
                ('year', models.IntegerField(max_length=4)),
                ('sinopsis', models.TextField(max_length=2000)),
            ],
        ),
    ]
