# Generated by Django 4.2 on 2024-07-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_pokemon_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pokemon',
            new_name='Movie',
        ),
    ]
